// this file is automatically generated using scripts/updatePackageVersions.js
export default {
  "route-active": "1.0.0-beta.11",
  "route-ancestors": "1.0.0-beta.10",
  "route-prefetch": "1.0.0-beta.16",
  "react-dom": "1.0.0-beta.4",
  "react-native": "1.0.0-beta.13",
  "react-universal": "1.0.0-beta.3",
  "router": "1.0.0-beta.43",
  "side-effect-aria-live": "1.0.0-beta.3",
  "side-effect-scroll": "1.0.0-beta.12",
  "side-effect-title": "1.0.0-beta.13",
  "svelte": "1.0.0-beta.8",
  "vue": "1.0.0-beta.23"
};
