// this file is automatically generated using scripts/updatePackageVersions.js
export default {
  "route-active": "1.0.0",
  "route-ancestors": "1.0.0",
  "route-prefetch": "1.0.0",
  "react-dom": "1.0.0",
  "react-native": "1.0.0",
  "react-universal": "1.0.0",
  "router": "1.0.0",
  "side-effect-aria-live": "1.0.0",
  "side-effect-scroll": "1.0.0",
  "side-effect-title": "1.0.0",
  "svelte": "1.0.0-beta.8",
  "vue": "1.0.0-beta.23"
};
