import React from "react";
import { Link } from "@curi/react";

import BasePackage from "./base/BasePackage";
import APIBlock from "./base/APIBlock";
import {
  PrismBlock,
  InlineJS as IJS,
  InlineComponent as Cmp
} from "../components/PrismBlocks";
import { Section } from "../components/Sections";

export default ({ name, version, globalName }) => (
  <BasePackage
    name={name}
    version={version}
    globalName={globalName}
    about={
      <p>
        This package allows you to synchronize the response objects generated by
        Curi with MobX. Whenever location changes occur, the store will be
        updated.
      </p>
    }
  >
    <APIBlock>
      <PrismBlock lang="javascript">
        {`import CuriStore from '@curi/mobx';`}
      </PrismBlock>

      <Section tag="h3" title="CuriStore" id="CuriStore">
        <p>
          <IJS>CuriStore</IJS> will store responses. When creating a store you
          just need to pass it your router and the store will automatically
          listen for new responses and update itself.
        </p>
        <PrismBlock lang="javascript">
          {`const router = curi(history, routes);
const curiStore = new CuriStore(router);`}
        </PrismBlock>
      </Section>
    </APIBlock>
  </BasePackage>
);
