// this file is automatically generated using scripts/updatePackageVersions.js
export default {
  "helpers": "2.0.0-alpha.0",
  "route-active": "2.0.0-beta.0",
  "route-ancestors": "2.0.0-alpha.0",
  "route-prefetch": "2.0.0-beta.0",
  "react-dom": "2.0.0-beta.0",
  "react-native": "2.0.0-beta.0",
  "react-universal": "2.0.0-beta.0",
  "router": "2.0.0-beta.2",
  "side-effect-aria-live": "1.0.2",
  "side-effect-scroll": "2.0.0-beta.0",
  "side-effect-title": "1.0.2",
  "static": "1.0.0-beta.1",
  "svelte": "1.0.0-beta.14",
  "vue": "1.0.0-beta.27"
};
