// this file is automatically generated
export default {
  "helpers": "2.0.0",
  "interactions": "2.0.0",
  "react-dom": "2.0.0",
  "react-native": "2.0.0",
  "react-universal": "2.0.0",
  "router": "2.0.1",
  "static": "2.0.1",
  "svelte": "2.0.0-beta.4",
  "types": "2.0.0",
  "vue": "2.0.0-alpha.11"
};
