// this file is automatically generated
export default {
  "helpers": "2.0.2",
  "interactions": "2.0.3",
  "react-dom": "2.0.4",
  "react-native": "2.0.4",
  "react-universal": "2.0.3",
  "router": "2.1.2",
  "static": "2.0.4",
  "svelte": "2.0.0-beta.6",
  "types": "2.0.2",
  "vue": "2.0.0-alpha.13"
};
