const join = require('path').join;
const fs = require('fs');

const BASE_PATH = join(__dirname, '..', '..', 'packages');
const OUTPUT_FILE = join(__dirname, '..', 'src', 'client', 'Packages', 'versions.js');
module.exports = function updatePackageVersions() {
  const mappedVersions = fs.readdirSync(BASE_PATH)
    .reduce((acc, file) => {
      if (!fs.lstatSync(join(BASE_PATH, file)).isDirectory()) {
        return acc;
      }
      const pkgFile = join(BASE_PATH, file, 'package.json');
      const pkg = require(pkgFile);
      acc[file] = pkg.version;
      return acc;
    }, {});

  fs.writeFile(
    OUTPUT_FILE,
    `// this file is automatically generated using scripts/updatePackageVersions.js
export default ${JSON.stringify(mappedVersions, null, 2)};\n`,
    function(err) {
      if (err) {
        console.error(err);
      }
    }
  );
}
