let glob = require("glob");
let path = require("path");
let fs = require("fs-extra");
let git = require("simple-git")(process.cwd());

let root = process.cwd();

let packagesDir = path.join(root, "packages");
let examplesDir = path.join(root, "examples");
let docsDir = path.join(root, "website");
let docConstantVersions = path.join(docsDir, "src", "constants", "versions.js");

console.log("Updating CHANGELOG versions...");
// This relies on a README beginning with the string "## Next".
// If those aren't the first seven characters of the file, this
// will fail.
glob.sync(`${packagesDir}/**/CHANGELOG.md`).forEach(readme => {
  let buffer = fs.readFileSync(readme);
  if (buffer.indexOf("## Next") !== 0) {
    return;
  }

  let pathname = readme.substr(0, readme.indexOf("/CHANGELOG.md"));
  let pkg = require(`${pathname}/package.json`);
  let versionBuffer = Buffer.from(`## ${pkg.version}`);
  let output = Buffer.concat([versionBuffer, buffer.slice(7)]);

  fs.outputFileSync(readme, output);
  git.add(readme);
});

console.log("Updating example dependencies...");
// get the dependencies from the actual packages
let pkgs = glob
  .sync(`${packagesDir}/**/package.json`)
  .map(pkgPath => require(pkgPath))
  .map(pkg => ({
    name: pkg.name,
    version: pkg.version
  }))
  .reduce((acc, curr) => {
    acc[curr.name] = curr.version;
    return acc;
  }, {});

glob
  .sync(`${examplesDir}/+(react|vue|svelte|misc)/*/package.json`)
  .map(pkgPath => ({
    path: pkgPath,
    module: require(pkgPath)
  }))
  .forEach(pkg => {
    Object.keys(pkg.module.dependencies).forEach(dep => {
      if (dep in pkgs) {
        pkg.module.dependencies[dep] = pkgs[dep];
      }
    });

    fs.outputFile(pkg.path, `${JSON.stringify(pkg.module, null, 2)}\n`).then(
      () => {
        git.add(pkg.path);
      },
      e => {
        console.error(`Failed to write ${pkg.path}`);
        console.error(e);
      }
    );
  });

console.log("Updating package versions in docs...");
let mappedVersions = Object.keys(pkgs).reduce((acc, name) => {
  acc[name.slice(6)] = pkgs[name];
  return acc;
}, {});

fs.writeFile(
  docConstantVersions,
  `// this file is automatically generated
export default ${JSON.stringify(mappedVersions, null, 2)};\n`,
  function(err) {
    if (err) {
      console.error(err);
    } else {
      git.add(docConstantVersions);
    }
  }
);
