// this file is automatically generated using scripts/updatePackageVersions.js
export default {
  "addon-active": "1.0.0-beta.5",
  "addon-ancestors": "1.0.0-beta.5",
  "addon-prefetch": "1.0.0-beta.6",
  "core": "1.0.0-beta.28",
  "mobx": "1.0.0-alpha.2",
  "react": "1.0.0-beta.20",
  "react-native": "1.0.0-beta.2",
  "redux": "1.0.0-beta.4",
  "side-effect-scroll": "1.0.0-beta.8",
  "side-effect-title": "1.0.0-beta.9",
  "svelte": "1.0.0-beta.4",
  "vue": "1.0.0-beta.16"
};
