// this file is automatically generated using scripts/updatePackageVersions.js
export default {
  "addon-active": "1.0.0-beta.5",
  "addon-ancestors": "1.0.0-beta.5",
  "addon-prefetch": "1.0.0-beta.5",
  "core": "1.0.0-beta.19",
  "react": "1.0.0-beta.13",
  "redux": "1.0.0-beta.1",
  "side-effect-scroll": "1.0.0-beta.5",
  "side-effect-title": "1.0.0-beta.5",
  "svelte": "1.0.0-beta.1",
  "vue": "1.0.0-beta.10"
};
